// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EMG.Migrations
{
    [DbContext(typeof(EMGDbContext))]
    partial class EMGDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EMG.Models.Key", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Keys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C Major"
                        },
                        new
                        {
                            Id = 2,
                            Name = "G Major"
                        },
                        new
                        {
                            Id = 3,
                            Name = "D Major"
                        },
                        new
                        {
                            Id = 4,
                            Name = "A Major"
                        },
                        new
                        {
                            Id = 5,
                            Name = "E Major"
                        },
                        new
                        {
                            Id = 6,
                            Name = "B Major"
                        },
                        new
                        {
                            Id = 7,
                            Name = "F# Major"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Db Major"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ab Major"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Eb Major"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Bb Major"
                        },
                        new
                        {
                            Id = 12,
                            Name = "F Major"
                        },
                        new
                        {
                            Id = 13,
                            Name = "A Minor"
                        },
                        new
                        {
                            Id = 14,
                            Name = "E Minor"
                        },
                        new
                        {
                            Id = 15,
                            Name = "B Minor"
                        },
                        new
                        {
                            Id = 16,
                            Name = "F# Minor"
                        },
                        new
                        {
                            Id = 17,
                            Name = "C# Minor"
                        },
                        new
                        {
                            Id = 18,
                            Name = "G# Minor"
                        },
                        new
                        {
                            Id = 19,
                            Name = "D# Minor"
                        },
                        new
                        {
                            Id = 20,
                            Name = "A# Minor"
                        },
                        new
                        {
                            Id = 21,
                            Name = "D Minor"
                        },
                        new
                        {
                            Id = 22,
                            Name = "G Minor"
                        },
                        new
                        {
                            Id = 23,
                            Name = "C Minor"
                        },
                        new
                        {
                            Id = 24,
                            Name = "F Minor"
                        });
                });

            modelBuilder.Entity("EMG.Models.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PaymentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Credit Card"
                        },
                        new
                        {
                            Id = 2,
                            Type = "PayPal"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Bank Transfer"
                        });
                });

            modelBuilder.Entity("EMG.Models.ProducerService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ProducerId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProducerId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ProducerServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Price = 100m,
                            ProducerId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Price = 150m,
                            ProducerId = 1,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Price = 200m,
                            ProducerId = 3,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 4,
                            Active = false,
                            Price = 180m,
                            ProducerId = 3,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Price = 130m,
                            ProducerId = 5,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            Price = 160m,
                            ProducerId = 5,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            Price = 120m,
                            ProducerId = 1,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            Price = 220m,
                            ProducerId = 3,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 9,
                            Active = false,
                            Price = 140m,
                            ProducerId = 5,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            Price = 170m,
                            ProducerId = 1,
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 11,
                            Active = false,
                            Price = 190m,
                            ProducerId = 3,
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            Price = 210m,
                            ProducerId = 5,
                            ServiceId = 5
                        });
                });

            modelBuilder.Entity("EMG.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Bpm")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompleteDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<int>("KeyId")
                        .HasColumnType("integer");

                    b.Property<string>("Lyric")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ProducerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Worktape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("KeyId");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("ProducerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bpm = 120,
                            CompleteDate = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            IsComplete = true,
                            KeyId = 1,
                            Lyric = "Now that it's all said and done\nI can't believe you were the one\nTo build me up and tear me down\nLike an old abandoned house\nWhat you said when you left\nJust left me cold and out of breath\nI fell too far, was in way too deep\nGuess I let you get the best of me\nWell, I never saw it coming\nI should've started running a long, long time ago\nAnd I never thought I'd doubt you\nI'm better off without you\nMore than you, more than you know\nI'm slowly getting closure\nI guess it's really over\nI'm finally getting better\nNow, I'm picking up the pieces\nAnd spending all of these years\nPutting my heart back together",
                            Notes = "Please make sure the vocalist sticks to the worktape melody.",
                            PaymentTypeId = 1,
                            ProducerId = 1,
                            StartDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Over You",
                            Worktape = "worktape_alpha.mp3"
                        },
                        new
                        {
                            Id = 2,
                            Bpm = 128,
                            CompleteDate = new DateTime(2023, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 4,
                            IsComplete = true,
                            KeyId = 2,
                            Lyric = "I'm gonna make a change\nFor once in my life\nIt's gonna feel real good\nGonna make a difference\nGonna make it right\nAs I, turn up the collar on\nMy favorite winter coat\nThis wind is blowin' my mind\nI see the kids in the street\nWith not enough to eat\nWho am I, to be blind pretending not to see their needs?\nA summer's disregard\nA broken bottle top\nAnd a one man's soul\nThey follow each other on the wind ya know\n'Cause they got nowhere to go\nThat's why I want you to know\nI'm starting with the man in the mirror\nI'm asking him to change his ways\nAnd no message could've been any clearer\nIf they wanna make the world a better place\nTake a look at yourself and then make a change",
                            Notes = "I'm shooting for an epic feel here, less pop and more a sync-vibe. If the tempo feels too fast feel free to slow it down a couple clicks",
                            PaymentTypeId = 2,
                            ProducerId = 3,
                            StartDate = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Man In The Mirror",
                            Worktape = "worktape_beta.mp3"
                        },
                        new
                        {
                            Id = 3,
                            Bpm = 110,
                            CompleteDate = new DateTime(2023, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 6,
                            IsComplete = true,
                            KeyId = 3,
                            Lyric = "Load up on guns, bring your friends\nIt's fun to lose and to pretend\nShe's over bored and self-assured\nOh, no, I know a dirty word\nHello, hello, hello, how low?\nHello, hello, hello, how low?\nHello, hello, hello, how low?\nHello, hello, hello\nWith the lights out, it's less dangerous\nHere we are now, entertain us\nI feel stupid and contagious\nHere we are now, entertain us\nA mulatto, an albino\nA mosquito, my libido, yeah\nHey\nYeah",
                            Notes = "This is a straight up rocker. I want the song to build throughout. If you need references I can send them.",
                            PaymentTypeId = 3,
                            ProducerId = 5,
                            StartDate = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Smells Like Teen Spirit",
                            Worktape = "worktape_gamma.mp3"
                        },
                        new
                        {
                            Id = 4,
                            Bpm = 135,
                            CustomerId = 2,
                            IsComplete = false,
                            KeyId = 4,
                            Lyric = "Spent 24 hours, I need more hours with you\nYou spent the weekend getting even, ooh\nWe spent the late nights making things right between us\nBut now it's all good, babe\nRoll that back wood, babe\nAnd play me close\n'Cause girls like you run 'round with guys like me\n'Til sun down when I come through\nI need a girl like you, yeah yeah\nGirls like you love fun and, yeah, me too\nWhat I want when I come through\nI need a girl like you, yeah yeah\nYeah yeah yeah, yeah yeah yeah\nI need a girl like you, yeah yeah\nYeah yeah yeah, yeah yeah yeah\nI need a girl like you",
                            Notes = "I'm hoping for a similar vibe to Morgan Wallen's 'Whiskey Glasses'.",
                            PaymentTypeId = 1,
                            ProducerId = 1,
                            StartDate = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "She's A City Girl Now",
                            Worktape = "worktape_delta.mp3"
                        },
                        new
                        {
                            Id = 5,
                            Bpm = 140,
                            CustomerId = 4,
                            IsComplete = false,
                            KeyId = 5,
                            Lyric = "I'm at a payphone, trying to call home\nAll of my change I spent on you\nWhere have the times gone? Baby, it's all wrong\nWhere are the plans we made for two?\nYeah, I, I know it's hard to remember\nThe people we used to be\nIt's even harder to picture\nThat you're not here next to me\nYou say it's too late to make it\nBut is it too late to try?\nAnd in our time that you wasted\nAll of our bridges burned down\nI've wasted my nights\nYou turned out the lights\nNow, I'm paralyzed\nStill stuck in that time\nWhen we called it love\nBut even the sun sets in paradise",
                            Notes = "I already hired the vocalist for this. She will be sending you the vocal stems as soon as she is done.",
                            PaymentTypeId = 2,
                            ProducerId = 3,
                            StartDate = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Payphone",
                            Worktape = "worktape_epsilon.mp3"
                        },
                        new
                        {
                            Id = 6,
                            Bpm = 118,
                            CompleteDate = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 6,
                            IsComplete = true,
                            KeyId = 6,
                            Lyric = "It must be your skin, I'm sinkin' in\nIt must be for real, 'cause now I can feel\nAnd I didn't mind, it's not my kind\nIt's not my time, to wonder why\nEverything gone white, everything's grey\nNow you're here, now you're away\nI don't want this, remember that\nI'll never forget, where you're at\nDon't let the days go by\nGlycerine, glycerine\nI'm never alone, I'm alone all the time\nAre you at one, or do you lie\nWe live in a wheel, where everyone steals\nBut when we rise, it's like strawberry fields\nIf I treated you bad, you'd bruise my face\nCouldn't love you more, you've got a beautiful taste",
                            Notes = "I'm hoping for an atmospheric vibe over the electric guitars.",
                            PaymentTypeId = 3,
                            ProducerId = 5,
                            StartDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Glycerine",
                            Worktape = "worktape_zeta.mp3"
                        },
                        new
                        {
                            Id = 7,
                            Bpm = 125,
                            CustomerId = 2,
                            IsComplete = false,
                            KeyId = 7,
                            Lyric = "You've got your ball\nYou've got your chain\nTied to me tight tie me up again\nWho's got their claws\nIn you my friend\nInto your heart I'll beat again\nSweet like candy to my soul\nSweet you rock\nAnd sweet you roll\nLost for you I'm so lost for you\nYou come crash into me\nAnd I come into you\nI come into you\nIn a boys dream\nIn a boys dream\nTouch your lips just so I know\nIn your eyes, love, it glows so\nI'm bare-boned and crazy for you\nWhen you come crash\nInto me, baby\nAnd I come into you\nIn a boys dream\nIn a boys dream\nIf I've gone overboard\nThen I'm begging you\nTo forgive me\nIn my haste\nWhen I'm holding you so girl\nClose to me",
                            Notes = "All acoustic on this one, no electric guitars please.",
                            PaymentTypeId = 1,
                            ProducerId = 1,
                            StartDate = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Crash",
                            Worktape = "worktape_eta.mp3"
                        },
                        new
                        {
                            Id = 8,
                            Bpm = 132,
                            CompleteDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 4,
                            IsComplete = true,
                            KeyId = 8,
                            Lyric = "End of passion play, crumbling away\nI'm your source of self-destruction\nVeins that pump with fear, sucking darkest clear\nLeading on your death's construction\nTaste me, you will see\nMore is all you need\nDedicated to\nHow I'm killing you\nCome crawling faster\nObey your master\nYour life burns faster\nObey your master, master\nMaster of puppets, I'm pulling your strings\nTwisting your mind and smashing your dreams\nBlinded by me, you can't see a thing\nJust call my name, 'cause I'll hear you scream\nMaster, master\nJust call my name, 'cause I'll hear you scream\nMaster, master",
                            Notes = "I'm thinking a Metallica vibe on this one!",
                            PaymentTypeId = 2,
                            ProducerId = 3,
                            StartDate = new DateTime(2023, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Master Of Puppets",
                            Worktape = "worktape_theta.mp3"
                        },
                        new
                        {
                            Id = 9,
                            Bpm = 115,
                            CompleteDate = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 6,
                            IsComplete = true,
                            KeyId = 9,
                            Lyric = "All the right friends in all the right places\nSo yeah, we're goin' down\nThey got all the right moves in all the right faces\nSo yeah, we're goin' down\nLet's paint the picture of the perfect place\nThey got it better than what anyone's told you\nThey'll be the King of Hearts, and you're the Queen of Spades\nThen we'll fight for you like we were your soldiers\nI know we got it good, but they got it made\nAnd their grass is getting greener each day\nI know things are looking up, but soon they'll take us down\nBefore anybody's knowin' our name\nThey got all the right friends in all the right places\nSo yeah, we're goin' down\nThey got all the right moves in all the right faces\nSo yeah, we're goin' down",
                            Notes = "This is for a pop pitch, so no country elements.",
                            PaymentTypeId = 3,
                            ProducerId = 5,
                            StartDate = new DateTime(2023, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "All The Right Moves",
                            Worktape = "worktape_iota.mp3"
                        },
                        new
                        {
                            Id = 10,
                            Bpm = 122,
                            CustomerId = 2,
                            IsComplete = false,
                            KeyId = 10,
                            Lyric = "'Cause you're a sky, 'cause you're a sky full of stars\nI'm gonna give you my heart\n'Cause you're a sky, 'cause you're a sky full of stars\n'Cause you light up the path\nI don't care, go on and tear me apart\nI don't care if you do, ooh-ooh, ooh\n'Cause in a sky, 'cause in a sky full of stars\nI think I saw you\n'Cause you're a sky, 'cause you're a sky full of stars\nI wanna die in your arms, oh, oh-oh\n'Cause you get lighter the more it gets dark\nI'm gonna give you my heart, oh",
                            Notes = "This is a special one to me, hoping to have it played for my fiance.",
                            PaymentTypeId = 1,
                            ProducerId = 1,
                            StartDate = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sky Full Of Stars",
                            Worktape = "worktape_kappa.mp3"
                        },
                        new
                        {
                            Id = 11,
                            Bpm = 138,
                            CustomerId = 4,
                            IsComplete = false,
                            KeyId = 11,
                            Lyric = "A full moon shinin' bright\nEdge of the water, we were feelin' alright\nBack down a country road\nThe girls are always hot, and the beer is ice cold\nCadillac, horns on the hood\nMy buddy Frankie had his dad hook him up good\nGirls smile when we roll by\nThey hop in the back, and we cruise to the river side\nNever gonna grow up (Whoa-oh)\nNever gonna slow down (Whoa-oh)\nWe were shinin' like lighters in the dark\nIn the middle of a rock show (Whoa-oh)\nWe were doin' it right (Whoa-oh)\nWe were comin' alive (Whoa-oh)\nYeah, caught in a southern summer, barefoot, blue jean night",
                            Notes = "I think some steel and a banjo would be great on this.",
                            PaymentTypeId = 2,
                            ProducerId = 3,
                            StartDate = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Barefoot Blue Jean Night",
                            Worktape = "worktape_lambda.mp3"
                        },
                        new
                        {
                            Id = 12,
                            Bpm = 130,
                            CustomerId = 6,
                            IsComplete = false,
                            KeyId = 12,
                            Lyric = "When I picked you up for our first date baby\nWell, your pretty blue eyes, they were drivin' me crazy\nAnd the tiny little thought that was so amazing\nIs they were looking at me.\nI held open the car door for you then you climbed\nInside and slid on over\nTo the other side, I thought my, oh my\nSweet thing\nThe moon is high and the night is young\nCome on and meet me\nIn the backyard under the Cottonwood tree\nIt's a good thing and I'm wishing\nC'mon sweet thing\nWon't you climb on out of your window\nWhile the world is sleeping\nYou know I need you\nAnd there's no way I'll be leaving\n'Till we're kissing on the porch swing\nOh my little sweet thing",
                            Notes = "This is just the first draft of the lyrics. Once the instrumental is done, I'll send a final lyric.",
                            PaymentTypeId = 3,
                            ProducerId = 5,
                            StartDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sweet Thing",
                            Worktape = "worktape_mu.mp3"
                        });
                });

            modelBuilder.Entity("EMG.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Recording service for tracks",
                            Name = "Recording"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mixing service for tracks",
                            Name = "Mixing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Mastering service for tracks",
                            Name = "Mastering"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Editing service for tracks",
                            Name = "Editing"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Producing service for tracks",
                            Name = "Producing"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Songwriting service for tracks",
                            Name = "Songwriting"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Arrangement service for tracks",
                            Name = "Arrangement"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Consultation for music projects",
                            Name = "Consultation"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Live recording service",
                            Name = "Live Recording"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Rehearsal space service",
                            Name = "Rehearsal"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Vocal tuning service",
                            Name = "Vocal Tuning"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Session musician service",
                            Name = "Session Musician"
                        });
                });

            modelBuilder.Entity("EMG.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsProducer")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.smith@example.com",
                            Image = "john_smith.png",
                            IsProducer = true,
                            Name = "John Smith",
                            Phone = "123-456-7890",
                            Uid = "UID001"
                        },
                        new
                        {
                            Id = 2,
                            Email = "mary.jane@example.com",
                            Image = "mary_jane.png",
                            IsProducer = false,
                            Name = "Mary Jane",
                            Phone = "234-567-8901",
                            Uid = "UID002"
                        },
                        new
                        {
                            Id = 3,
                            Email = "bob.doe@example.com",
                            Image = "bob_doe.png",
                            IsProducer = true,
                            Name = "Bob Doe",
                            Phone = "345-678-9012",
                            Uid = "UID003"
                        },
                        new
                        {
                            Id = 4,
                            Email = "alice.chan@example.com",
                            Image = "alice_chan.png",
                            IsProducer = false,
                            Name = "Alice Chan",
                            Phone = "456-789-0123",
                            Uid = "UID004"
                        },
                        new
                        {
                            Id = 5,
                            Email = "ryan.lee@example.com",
                            Image = "ryan_lee.png",
                            IsProducer = true,
                            Name = "Ryan Lee",
                            Phone = "567-890-1234",
                            Uid = "UID005"
                        },
                        new
                        {
                            Id = 6,
                            Email = "kiran.patel@example.com",
                            Image = "kiran_patel.png",
                            IsProducer = false,
                            Name = "Kiran Patel",
                            Phone = "678-901-2345",
                            Uid = "UID006"
                        });
                });

            modelBuilder.Entity("ProjectServices", b =>
                {
                    b.Property<int>("ProducerServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("ProducerServiceId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectServices");
                });

            modelBuilder.Entity("EMG.Models.ProducerService", b =>
                {
                    b.HasOne("EMG.Models.User", "Producer")
                        .WithMany("ProducerServices")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMG.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producer");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("EMG.Models.Project", b =>
                {
                    b.HasOne("EMG.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMG.Models.Key", "Key")
                        .WithMany()
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMG.Models.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMG.Models.User", "Producer")
                        .WithMany()
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Key");

                    b.Navigation("PaymentType");

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("ProjectServices", b =>
                {
                    b.HasOne("EMG.Models.ProducerService", null)
                        .WithMany()
                        .HasForeignKey("ProducerServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMG.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EMG.Models.User", b =>
                {
                    b.Navigation("ProducerServices");
                });
#pragma warning restore 612, 618
        }
    }
}
